language: generic

sudo: false

env:
   - COVERAGE=no
   - COVERAGE=yes COV_PROGRAM="bashcov --"
before_script:
   - git clone https://github.com/albfan/bashcov.git
   - cd bashcov/
   - gem build bashcov.gemspec 
   - gem install bashcov-1.2.1.gem 
   - cd ..
   - rm -rf bashcov
   - gem install codecov
   - gem install codeclimate-test-reporter
   - export PATH=$PATH:$PWD

script: 
   - ./autogen.sh
   - cd t 
   - make check

notifications:
  email:
    -  albertofanjul@gmail.com
